export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGOUT = 'LOGOUT'
export const GET_PROD = 'GET_PROD'
export const GET_TICKET = 'GET_TICKET'
export const GET_TICKET_BY_NUMBER = 'GET_TICKET_BY_NUMBER'
export const GET_TICKET_BY_ID = 'GET_TICKET_BY_ID'
export const POST_TICKET = 'POST_TICKET'
export const UDPATE_TICKET = 'UPDATE_TICKET'
export const GET_FARMER = 'GET_FARMER'
export const FILTER_TICKET = 'FILTER_TICKET'


